In [3]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(20, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df.groupby("性別")[['國文', '英文', '數學', '地理', '歷史']].agg('mean')

           國文         英文         數學         地理         歷史
性別
女   58.761905  64.714286  60.619048  64.571429  59.952381
男   54.586207  61.827586  59.241379  57.379310  59.241379

In [4]:
scores_df

     國文  英文   數學   地理  歷史   姓名 性別
1    55  33   22   75  64  劉彥宏  男
2    70  89   46   46  93  曾彥廷  男
3    69  90   95   76  74  吳子睿  男
4    27  81   49   90  27  蕭志明  男
5    23  75   70   60  91  王文傑  男
6    46  82   27   99  49  朱冠霖  男
7    35  33   85   57  97  謝欣蓉  女
8    85  52   33   73  48  羅淑芬  女
9    52  87   96   95  39  許美慧  女
10   40  35   39   21  48  廖志豪  男
11   28  57   91   83  70  葉柏翰  男
12   28  22   24   20  63  呂承恩  男
13   48  94  100   46  86  蘇雅婷  女
14   66  44   69   89  37  高浩宇  男
15   22  24   24   71  75  王婉茹  女
16   52  32   83   44  58  莊承翰  男
17   59  45   66   20  41  黃裕傑  男
18   43  44   98   33  63  王冠廷  男
19   57  33   60   21  55  呂婉慧  女
20   80  77   99   28  92  莊子謙  男
21   65  90   77   96  97  蘇彥宏  男
22   94  61   28   37  33  李柏融  男
23   44  93   26   38  49  曾明軒  男
24   89  93   67   66  77  呂佳瑩  女
25   59  39   95   91  80  洪怡君  女
26   57  21   24   46  98  洪柏宏  男
27   55  80   58   48  92  江雅琪  女
28   49  71   63   86  22  郭怡萱  女
29   59  75   66   52  89  簡婉慧  女
30   82  82   88   76  26  楊靜宜  女
31   83  44   55   39  59  曾靜儀  女
32   27  39   95   85  52  蕭怡伶  女
33   98  57   29   58  32  洪裕豪  男
34  100  30   59  100  47  簡建宏  男
35   55  66   91   85  78  劉浩然  男
36   24  46   44   32  65  蕭浩宇  男
37   77  54   25   28  33  呂怡靜  女
38   38  45   42   29  64  邱宗翰  男
39   38  83   52   25  35  彭美慧  女
40   68  88   22   81  42  劉靜芬  女
41   77  93   50   87  80  許淑芬  女
42   90  86   77   38  42  邱裕豪  男
43   38  68   58   76  47  吳雅萍  女
44   41  79   92   38  56  施子軒  男
45   43  88   76   93  56  莊柏融  男
46   35  95   87   36  75  鍾浩銘  男
47   79  79   58   70  53  周美玲  女
48   55  48   23   83  72  劉婉婷  女
49   20  36   50   69  21  曾明哲  男
50   93  94   38   85  35  詹柏翰  男

In [5]:
scores_df['總分'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)

scores_df['總分階級'] = pd.cut(
    scores_df['總分'],
    bins=[0, 250, 350, 500],
    labels=['低分區', '一般區', '高分區']
)

scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

         count        mean  min  max
性別 總分階級
女  低分區       4  223.000000  216  233
   一般區      11  304.454545  280  341
   高分區       6  373.333333  354  392
男  低分區       9  215.666667  157  250
   一般區      15  306.600000  253  345
   高分區       5  387.200000  356  425